### ISSUE TITLE
Upgraded to latest and now get "ModuleNotFoundError: No module named 'oauth2client.client"

### ISSUE THREAD

**Issue by maltokyo** [jay0lee/got-your-back#206]
Upgraded with git pull to the latest, and now get this for any operation:

`Traceback (most recent call last):
  File "/root/got-your-back/got-your-back/gyb.py", line 68, in <module>
    import oauth2client.client
ModuleNotFoundError: No module named 'oauth2client.client'`

Tried with -1 option too.  How to install what is missing, on Ubuntu 18.04

Thank you

**Comment by jay0lee** [comment]
Run

    pip install -r requirements.txt

Or just use one of the binary releases.

**Comment by maltokyo** [comment]
Thank you, installed all but still did not work.

```
Traceback (most recent call last):
  File "/root/got-your-back/got-your-back/gyb.py", line 68, in <module>
    import oauth2client.client
ModuleNotFoundError: No module named 'oauth2client.client'
```


> # pip install -r requirements.txt
Collecting oauth2client (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/95/a9/4f25a14d23f0786b64875b91784607c2277eff25d48f915e39ff0cff505a/oauth2client-4.1.3-py2.py3-none-any.whl (98kB)
    100% |████████████████████████████████| 102kB 1.7MB/s 
Collecting google-api-python-client (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/7a/84/ffde3c95d4162cdc8bae710fecc6873cccb05ac33afc3b2c925c74cc0150/google-api-python-client-1.7.8.tar.gz (141kB)
    100% |████████████████████████████████| 143kB 2.8MB/s 
Collecting httplib2>=0.9.1 (from oauth2client->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/67/33/29779c5aaeac796679a37bf798b3c2adbfaae7dbf13e966b0ab9c3aa06c0/httplib2-0.12.3.tar.gz (219kB)
    100% |████████████████████████████████| 225kB 2.7MB/s 
Collecting rsa>=3.1.4 (from oauth2client->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting pyasn1>=0.1.7 (from oauth2client->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 4.9MB/s 
Collecting pyasn1-modules>=0.0.5 (from oauth2client->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/91/f0/b03e00ce9fddf4827c42df1c3ce10c74eadebfb706231e8d6d1c356a4062/pyasn1_modules-0.2.5-py2.py3-none-any.whl (74kB)
    100% |████████████████████████████████| 81kB 5.1MB/s 
Requirement already satisfied: six>=1.6.1 in /usr/lib/python2.7/dist-packages (from oauth2client->-r requirements.txt (line 1))
Collecting google-auth-httplib2>=0.0.3 (from google-api-python-client->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/33/49/c814d6d438b823441552198f096fcd0377fd6c88714dbed34f1d3c8c4389/google_auth_httplib2-0.0.3-py2.py3-none-any.whl
Collecting google-auth>=1.4.1 (from google-api-python-client->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/c5/9b/ed0516cc1f7609fb0217e3057ff4f0f9f3e3ce79a369c6af4a6c5ca25664/google_auth-1.6.3-py2.py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 5.5MB/s 
Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/f6/25/66a49231b44409d7f07cfcf2506a8b070ce3c99fc47cc256bea833f24791/uritemplate-3.0.0-py2-none-any.whl
Collecting cachetools>=2.0.0 (from google-auth>=1.4.1->google-api-python-client->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/39/2b/d87fc2369242bd743883232c463f28205902b8579cb68dcf5b11eee1652f/cachetools-3.1.0-py2.py3-none-any.whl
Building wheels for collected packages: google-api-python-client, httplib2
  Running setup.py bdist_wheel for google-api-python-client ... done
  Stored in directory: /root/.cache/pip/wheels/47/59/2a/99d7513987cb500f6efa2866caf027a1b69793156f5052bc64
  Running setup.py bdist_wheel for httplib2 ... done
  Stored in directory: /root/.cache/pip/wheels/9d/0d/4f/10dbcd8796ba5943695b7b32f02f0cce68b698be7e2bb1d177
Successfully built google-api-python-client httplib2
Installing collected packages: httplib2, pyasn1, rsa, pyasn1-modules, oauth2client, cachetools, google-auth, google-auth-httplib2, uritemplate, google-api-python-client
Successfully installed cachetools-3.1.0 google-api-python-client-1.7.8 google-auth-1.6.3 google-auth-httplib2-0.0.3 httplib2-0.12.3 oauth2client-4.1.3 pyasn1-0.4.5 pyasn1-modules-0.2.5 rsa-4.0 uritemplate-3.0.0

**Comment by jay0lee** [comment]
You need to use the pip that is associated with your python3 install, not Python 2. Try running it again with pip3 instead of just pip. Also, what does pip -V show?

**Comment by maltokyo** [comment]
Apologies for bothering you with this, I reinstalled with pip3
```
# pip3 -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```
But still getting now a different set of errors when running the main script.


`# python3 /root/got-your-back/got-your-back/gyb.py --email mail1@gmail.com --action backup && python3 /root/got-your-back/got-your-back/gyb.py --email mail2@gmail.com --action restore --local-folder GYB-GMail-Backup-mail1@gmail.com --label-restored "$(date +"%Y%m%d")-gyb-mail1@gmail.com"

Traceback (most recent call last):
  File "/root/got-your-back/got-your-back/gyb.py", line 2071, in <module>
    main(sys.argv[1:])
  File "/root/got-your-back/got-your-back/gyb.py", line 1391, in main
    doGYBCheckForUpdates(debug=options.debug)
  File "/root/got-your-back/got-your-back/gyb.py", line 422, in doGYBCheckForUpdates
    (_, c) = anonhttpc.request(check_url, u'GET', headers=headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1313, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1063, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 986, in _conn_request
    conn.connect()
  File "/usr/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:847)`

**Comment by jay0lee** [comment]
- Don't run GYB as root. This is a bad idea and very insecure. GYB requires no special privileges and should be run as a regular user.
- Consider just using one of the binary releases of GYB, these already have all the libraries compiled, has Python 3.7 built-in and tested and make upgrading much simpler.

**Comment by maltokyo** [comment]
ok, thank you!  I liked being able to upgrade with git pull.  But I guess I will give up on that.
Will the binaries use all my existing databases and local directories etc?

**Comment by maltokyo** [comment]
Tried now from non-root user, different issues

`mal@otp7:~$ bash <(curl -s -S -L https://git.io/gyb-install)
This Linux distribution uses glibc 2.27
Using GYB compiled against glibc2.23

Checking GitHub URL https://api.github.com/repos/jay0lee/got-your-back/releases for  GYB release...

Getting file and download URL...

Downloading file gyb-1.25-linux-x86_64-glibc2.23.tar.xz from https://github.com/jay0lee/got-your-back/releases/download/v1.25/gyb-1.25-linux-x86_64-glibc2.23.tar.xz to /tmp/tmp.plneJtRwZ7.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   628    0   628    0     0   1670      0 --:--:-- --:--:-- --:--:--  1670
100 7377k  100 7377k    0     0  4000k      0  0:00:01  0:00:01 --:--:-- 6756k
Extracting archive to /home/mal/bin

Finished extracting GYB archive.

Please enter your email address: mail1@gmail.com

Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/v2/auth?client_id=297408095146-fug707qsjv4ikron0hugpevbrjhkmsk7.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&login_hint=mal%40malpage.com&access_type=online&response_type=code

Enter verification code: 4/RgGUm44F5Vss_9MrbShFc82y1ee_XF91SCwWYNCMq3BQCXJJ9MXl4zE
Authentication successful.
Creating project "Got Your Back Project"...
Checking project status...
ERROR: tried to retrieve https://raw.githubusercontent.com/jay0lee/got-your-back/master/project-apis.txt? but got 404
Project creation complete.`

**Comment by jay0lee** [comment]
Just pushed 1.26 now that should fix that issue, can you try the install command again now? Note that it may take a few tries before it sees GYB 1.26 correctly due to propagation delays on GitHub's side.

**Comment by maltokyo** [comment]
Still get this, but I am not sure if I am pulling 1.26 or not

> ERROR: tried to retrieve https://raw.githubusercontent.com/jay0lee/got-your-back/master/project-apis.txt? but got 404

**Comment by maltokyo** [comment]
Yes, it is 1.26, same issue

> Getting file and download URL...

Downloading file gyb-1.26-linux-x86_64-glibc2.23.tar.xz from https://github.com/jay0lee/got-your-back/releases/download/v1.26/gyb-1.26-linux-x86_64-glibc2.23.tar.xz to /tmp/tmp.TvgnRhaoAV.

**Comment by jay0lee** [comment]
OK, found one more issue. Just pushed 1.27, can you try again now?

**Comment by maltokyo** [comment]
OK, it is working, but became super complex..   I jumped through a lot of hoops on google pages, with all the codes, and now stuck again here:

```
Are you ready to authorize GYB to backup and restore G Suite user email? (yes or no) yes
Great! Checking service account scopes.This will fail the first time. Follow the steps to authorize and retry. It can take a few minutes for scopes to PASS after they've been authorized in the admin console.

 Scope: https://mail.google.com/                                     FAIL
 Scope: https://www.googleapis.com/auth/apps.groups.migration        FAIL
 Scope: https://www.googleapis.com/auth/drive.appdata                PASS

SOME SCOPES FAILED! Please go to:

https://admin.google.com/MYDOMAIN.com/AdminHome?#OGX:ManageOauthClients

and grant Client name:

110341065347914974573

Access to scopes:

https://mail.google.com/,
https://www.googleapis.com/auth/apps.groups.migration,
https://www.googleapis.com/auth/drive.appdata
```

The issue is, that on this page:
https://admin.google.com/MYDOMAIN.com/AdminHome?#OGX:ManageOauthClients
It will only allow one of the above scopes at a time.  When I enter one, the other one gets deleted.  It only allows one.  Without all three, your script will not continue.

Can we still use old versions?  This seems like a lot has changed, and it is scary giving so many authorisations.  Why does it need access to google drive (for example)?
