### ISSUE TITLE
python3 changes cause errors 

### ISSUE THREAD

**Issue by dude2511** [jay0lee/got-your-back#60]
I am using version 0.41 and python 3.4
1) If lastcheck.txt has not been created yet, it fails with "str does not support the buffer interface". Workaround is to manually write the text file with the timestamp.
2) When using a service account the type error "the JSON object must be str, not 'bytes'" appears. Fallback to non service account method was necessary.

**Comment by dude2511** [comment]
i fixed the second issue by decoding the object to an utf-8 string (around line 414)

`json_string = open(oauth2servicefilejson, 'rb').read().decode('utf-8')`

**Comment by oakleyding** [comment]
I got these two issues too. And after patched as @jonegerton said, still get error at line 300.
I think it because the lastcheck.txt is empty. It can be fixed after date +%s > lastcheck.txt.

**Comment by dougjuh** [comment]
See my simple solution to issue #57.

**Comment by jay0lee** [comment]
should be fixed in 0.43.
