### ISSUE TITLE
No way to ignore message specific errors

### ISSUE THREAD

**Issue by turbo2ltr** [jay0lee/got-your-back#62]
I had high hopes for this software.  I know, it's free, what do I expect...

Trying to restore messages.  28,000.  I started last week and it's still not complete. Super slow, which I could deal with, but the process was interrupted several times by a "500 backend error" and had to be restarted. Good news is it did seem to pick up where it left off.  But this ticket is not about that.

Its about this:
```
restoring 10 messages (5393/17884)
restored 0 messages (5393/17884)
restoring 10 messages (5403/17884)
restored 0 messages (5403/17884)
restoring 10 messages (5413/17884)
restored 0 messages (5413/17884)
restoring 10 messages (5423/17884)
restored 0 messages (5423/17884)
restoring single large message (5432/17884)

400: BadAttachment badfile_checker:EXE_FILE_FOUND - invalidArgument
```

I can't get past this point. I understand gmail doesn't allow exe file attachments (even though the archive was generated from a gmail account). Seems there should be an option to skip the attachments in these messages, or the whole message, and continue with the restore. At this point I don't see a way to get to the rest of the archive, making it quite useless as a backup medium.

**Comment by oakleyding** [comment]
Got same issue, and a workaround:
download a sqlite tool, open the xxxx@gmail.com-restored.sqlite
add a row to last number+1, it will let gyb think this record is already restored then start from next one.
Or if got error like:

    restoring single large message (86/6355)
    400: BadAttachment badfile_checker_ac:EXE_FILE_FOUND - invalidArgument

Re-run gyb, then will got a small number.

    restoring single large message (5/6269)
    400: BadAttachment badfile_checker_ac:EXE_FILE_FOUND - invalidArgument

just add a row that last number + the number here is 5.
It's not good workaround, only workable, hope someone can fix it by a normal way.

**Comment by jay0lee** [comment]
This should be fixed in 0.43 release. The error will still print and the message will not be restored but restoration will continue.

**Comment by subibro** [comment]
I am running v0.44 and still get this issue. I keep trying and it eventually goes through but makes restoring a tedious multi-day task.
Any ideas?

**Comment by tiemen** [comment]
I still have this issue in 0.45. The workaround described by @oakleyding isn't working for me. @jay0lee, can it be reopened?
